New compose folder

diff --git a/dev/compose/aap.yaml b/dev/compose/aap.yaml
--- a/dev/compose/aap.yaml
+++ b/dev/compose/aap.yaml
@@ -1,5 +1,7 @@
 x-common-env: &common-env
 
+  GNUPGHOME: /root/.gnupg/
+
   DJANGO_SUPERUSER_USERNAME: admin
   DJANGO_SUPERUSER_EMAIL: admin@example.com
   DJANGO_SUPERUSER_PASSWORD: admin
@@ -59,11 +61,17 @@ x-common-env: &common-env
   # role content workaround ..
   PULP_ANSIBLE_BASE_ROLES_REQUIRE_VIEW: 'false'
 
+  # DEV EDITABLE STUFF
+  LOCK_REQUIREMENTS: 0
+  DEV_SOURCE_PATH: "galaxy_ng"
+  # To enable editable installs of local checkouts change the variable above keeping the ordering as follows:
+  # DEV_SOURCE_PATH: "dynaconf:pulpcore:galaxy_importer:pulp_ansible:pulp_container:galaxy_ng:django-ansible-base"
+
 
 services:
   base_img:
     build:
-      context: .
+      context: ..
       dockerfile: Dockerfile
     image: "localhost/galaxy_ng/galaxy_ng:base"
 
@@ -78,8 +86,8 @@ services:
       test: ["CMD", "pg_isready", "-U", "galaxy_ng"]
       interval: 10s
       retries: 5
- 
-  helper:
+
+  helper:  # should this be moved to a custom Dockerfile?
     image: quay.io/centos/centos:stream9
     environment:
       <<: *common-env
@@ -88,24 +96,30 @@ services:
     volumes:
       - "etc_pulp_certs:/etc/pulp/certs"
       - "var_lib_pulp:/var/lib/pulp"
+      - "../../../:/src"
     command: |
       bash -c "
-        if [[ ! -e /etc/pulp/certs/database_fields.symmetric.key ]] || [[ -s /etc/pulp/certs/database_fields.symmetric.key ]]; then
-          mkdir -p /etc/pulp/certs/;
-          echo 'check openssl and install ...';
-          rpm -q openssl || dnf -y install openssl;
-          echo 'generate key ...';
-          openssl rand -base64 32 > /etc/pulp/certs/database_fields.symmetric.key;
-          echo 'chown key ...';
-          chmod 640 /etc/pulp/certs/database_fields.symmetric.key;
-        else
-          echo 'symmetric key exists'
-        fi;
-        find /etc/pulp ;
-        echo '# KEY >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>';
-        cat /etc/pulp/certs/database_fields.symmetric.key;
-        echo '<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<';
-        echo "DONE!";
+        echo 'Moving required files to the required places.';
+
+        # Workarounds - Pulp SigningService can't access envvars;
+        /src/galaxy_ng/dev/compose/signing/setup_gpg_workarounds.sh;
+        cat /etc/pulp/certs/GNUPGHOME.workaround.txt;
+        cat /etc/pulp/certs/HOME.workaround.txt;
+
+        # Keys;
+        cp /src/galaxy_ng/dev/compose/database/database_fields.symmetric.key /etc/pulp/certs/database_fields.symmetric.key;
+        cp /src/galaxy_ng/dev/compose/signing/signing-secret.key /etc/pulp/certs/signing-secret.key
+        cp /src/galaxy_ng/dev/compose/signing/signing-secret.key.password.txt /etc/pulp/certs/signing-secret.key.password.txt
+        cp /src/galaxy_ng/dev/compose/signing/signing-secret.key /etc/pulp/certs/signing-public.key
+        find /etc/pulp/certs;
+
+        # Scripts;
+        cp /src/galaxy_ng/dev/compose/signing/collection_sign.sh /var/lib/pulp/scripts/collection_sign.sh;
+        cp /src/galaxy_ng/dev/compose/signing/container_sign.sh /var/lib/pulp/scripts/container_sign.sh;
+        chmod +x /var/lib/pulp/scripts/*_sign.sh;
+        find /var/lib/pulp/scripts;
+
+        echo 'DONE!';
       "
 
   migrations:
@@ -117,22 +131,24 @@ services:
     volumes:
       - "etc_pulp_certs:/etc/pulp/certs"
       - "var_lib_pulp:/var/lib/pulp"
-      - ".:/src/galaxy_ng"
+      - "../../../:/src"
     environment:
       <<: *common-env
     user: root
     command: |
       bash -c "
         set -e;
+        rm -rf /var/lib/pulp/.migrated;
         while [[ ! -f /etc/pulp/certs/database_fields.symmetric.key ]]; do
           echo 'Waiting for key';
           sleep 2;
         done;
+        /src/galaxy_ng/dev/compose/bin/devinstall;
         pulpcore-manager check --database default;
         pulpcore-manager migrate;
-        touch /var/lib/pulp/.migrated;
         pulpcore-manager shell < /src/galaxy_ng/dev/common/setup_test_data.py;
-        pulpcore-manager createsuperuser --noinput;
+        pulpcore-manager createsuperuser --noinput || true;
+        touch /var/lib/pulp/.migrated;
       "
 
   api:
@@ -145,7 +161,7 @@ services:
     volumes:
       - "etc_pulp_certs:/etc/pulp/certs"
       - "var_lib_pulp:/var/lib/pulp"
-      - ".:/src/galaxy_ng"
+      - "../../../:/src"
     environment:
       <<: *common-env
     extra_hosts:
@@ -153,12 +169,16 @@ services:
     networks:
       - default
       - service-mesh
+    user: root
     command: |
       bash -c "
         while [[ ! -f /var/lib/pulp/.migrated ]]; do
           echo 'Waiting for migrations ...';
           sleep 2;
-        done && exec pulpcore-api --reload;
+        done;
+
+        /src/galaxy_ng/dev/compose/bin/devinstall;
+        /src/galaxy_ng/dev/compose/bin/reloader /venv/bin/pulpcore-api
       "
 
   content:
@@ -171,7 +191,7 @@ services:
     volumes:
       - "etc_pulp_certs:/etc/pulp/certs"
       - "var_lib_pulp:/var/lib/pulp"
-      - ".:/src/galaxy_ng"
+      - "../../../:/src"
     environment:
       <<: *common-env
     extra_hosts:
@@ -179,12 +199,16 @@ services:
     networks:
       - default
       - service-mesh
+    user: root
     command: |
       bash -c "
         while [[ ! -f /var/lib/pulp/.migrated ]]; do
           echo 'Waiting for migrations ...';
           sleep 2;
-        done && exec pulpcore-content --reload;
+        done;
+
+        /src/galaxy_ng/dev/compose/bin/devinstall;
+        /src/galaxy_ng/dev/compose/bin/reloader /venv/bin/pulpcore-content
       "
 
   worker:
@@ -197,15 +221,87 @@ services:
     volumes:
       - "etc_pulp_certs:/etc/pulp/certs"
       - "var_lib_pulp:/var/lib/pulp"
-      - ".:/src/galaxy_ng"
+      - "../../../:/src"
     environment:
       <<: *common-env
+    user: root
     command: |
       bash -c "
         while [[ ! -f /var/lib/pulp/.migrated ]]; do
           echo 'Waiting for migrations ...';
           sleep 2;
-        done && exec pulpcore-worker;
+        done;
+        while [[ ! -f /etc/pulp/certs/signing-secret.key ]]; do
+          echo 'Waiting for signing key';
+          sleep 2;
+        done;
+
+        # Worker needs gpg in order to consume signing tasks;
+        /src/galaxy_ng/dev/compose/signing/setup_gpg_keys.sh;
+        gpg --list-secret-keys;
+
+        /src/galaxy_ng/dev/compose/bin/devinstall;
+        /src/galaxy_ng/dev/compose/bin/reloader /venv/bin/pulpcore-worker
+      "
+
+  manager:
+    image: "localhost/galaxy_ng/galaxy_ng:base"
+    depends_on:
+      - base_img
+      - postgres
+      - helper
+      - migrations
+      - worker
+    volumes:
+      - "etc_pulp_certs:/etc/pulp/certs"
+      - "var_lib_pulp:/var/lib/pulp"
+      - "../../../:/src"
+    environment:
+      <<: *common-env
+    user: root
+    command: |
+      bash -c "
+        while [[ ! -f /var/lib/pulp/.migrated ]]; do
+          echo 'Waiting for migrations ...';
+          sleep 2;
+        done;
+        while [[ ! -f /etc/pulp/certs/signing-secret.key ]]; do
+          echo 'Waiting for signing key';
+          sleep 2;
+        done;
+
+        /src/galaxy_ng/dev/compose/bin/devinstall;
+
+        # Schedule resource sync;
+        pulpcore-manager task-scheduler --id dab_sync --interval 15 --path "galaxy_ng.app.tasks.resource_sync.run";
+        curl -s -u admin:admin http://api:24817/api/galaxy/pulp/api/v3/task-schedules/?name=dab_sync | python -m json.tool;
+
+        # Keys are needed to register signing services;
+        /src/galaxy_ng/dev/compose/signing/setup_gpg_keys.sh;
+        gpg --list-secret-keys;
+
+        # Setup signing services;
+        /src/galaxy_ng/dev/compose/signing/setup_signing_services.sh;
+        curl -s -u admin:admin http://api:24817/api/galaxy/pulp/api/v3/signing-services/?fields=name,script,pubkey_fingerprint | python -m json.tool;
+
+        # Setup repository gpgkey for upload verification;
+        /src/galaxy_ng/dev/compose/signing/setup_repo_keyring.sh
+
+        # Dev tools; SHOULD THIS MOVE TO A CUSTOM Dockerfile?
+        /venv/bin/pip3.11 install ipython ipdb django-extensions;
+
+        echo ' ';
+        echo '###################### API ROOT ##############################';
+        curl -s http://api:24817/api/galaxy/ | python -m json.tool;
+
+        echo '######################## READY ###############################';
+        echo ' ';
+        echo 'API: http://localhost:5001/api/galaxy/v3/swagger-ui/';
+        echo 'Django Admin CLI: docker compose -f aap_compose_dev.yaml exec manager pulpcore-manager';
+        echo 'Settings list: docker compose -f aap_compose_dev.yaml exec manager dynaconf list';
+
+        # Keep it running indefinitely to enable `docker compose -f ... exec manager /bin/bash`
+        tail -f /dev/null
       "
 
   nginx:
@@ -220,13 +316,13 @@ services:
     ports:
       - '5001:5001'
     volumes:
-      - './dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
+      - '../nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
 
 volumes:
   var_lib_pulp:
-    name: var_lib_pulp 
+    name: var_lib_pulp
   etc_pulp_certs:
-    name: etc_pulp_certs 
+    name: etc_pulp_certs
 
 networks:
   service-mesh:
