dont run tests if API is offline

diff --git a/.github/workflows/ci-docker-compose-integration.yml b/.github/workflows/ci-docker-compose-integration.yml
--- a/.github/workflows/ci-docker-compose-integration.yml
+++ b/.github/workflows/ci-docker-compose-integration.yml
@@ -74,6 +74,11 @@ jobs:
               echo "API online."
               exit 0
             fi
+
+            if [ $i -eq $max_runs ]; then
+              echo "Failed to start API after $max_runs retries."
+              exit 1
+            fi
           done
 
       - name: Install integration requirements
